# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pwa CI

on:
  push:
    branches: [ develop, release, master ]
  pull_request:
    branches: [ develop, release, master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm run test:coverage    

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests            # Name of the check run which will be created
        path: perf/reports/junit.xml # Path to test results
        reporter: jest-junit        # Format of test results        

    - name: Test Coverage Report
      uses: artiomtr/jest-coverage-report-action@v1.3
      with:
        name: JEST Tests Coverage           # Name of the check run which will be created
        github_token: ${{ secrets.GITHUB_TOKEN }}  
        threshold: 30      

